export const DB_SCHEMA_VERSION=1;
export const POSITIONS=['GK','RB','CB','LB','CDM','CM','CAM','RM','RW','LM','LW','ST','CF'];
export const FEET=['Right','Left','Both'];
export const ADDITIONAL_PLAYER_AUTO_THRESHOLD=18;
export function additionalPlayerGenerationMode(club){
 const raw=String(club?.additionalPlayerGeneration||'').trim().toLowerCase();
 if(['auto','always','off'].includes(raw))return raw;
 if(club?.generateAdditionalPlayers===false)return 'off';
 if(club?.generateAdditionalPlayers===true)return 'always';
 return 'auto';
}
export function shouldGenerateAdditionalPlayers(club,databasePlayerCount=0){
 const mode=additionalPlayerGenerationMode(club);
 if(mode==='always')return true;
 if(mode==='off')return false;
 return Math.max(0,Number(databasePlayerCount)||0)<ADDITIONAL_PLAYER_AUTO_THRESHOLD;
}
export const DATA_FILES={
 'data/confederations.json':'confederations','data/nations.json':'nations','data/leagues.json':'leagues','data/league_flow.json':'leagueFlows','data/clubs.json':'clubs','data/players.json':'players','data/competitions.json':'competitions','data/metadata.json':'metadata'
};
export const emptyData=()=>({confederations:[],nations:[],leagues:[],leagueFlows:[],clubs:[],players:[],competitions:[],metadata:{}});
export function clone(v){try{return structuredClone(v)}catch{return JSON.parse(JSON.stringify(v))}}
export function hashText(value){let h=2166136261;const t=String(value??'');for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36).padStart(7,'0')}
function stableStringify(value){const seen=new WeakSet();const n=input=>{if(input==null||typeof input!=='object')return input;if(seen.has(input))return '[Circular]';seen.add(input);if(Array.isArray(input))return input.map(n);const out={};for(const k of Object.keys(input).sort())out[k]=n(input[k]);return out};return JSON.stringify(n(value))}
export function contentHash(data){const dl=list=>(Array.isArray(list)?list:[]).map(x=>hashText(stableStringify(x)));return `kfm-${hashText(stableStringify({confederations:dl(data.confederations),nations:dl(data.nations),leagues:dl(data.leagues),leagueFlows:dl(data.leagueFlows),clubs:dl(data.clubs),players:dl(data.players),competitions:dl(data.competitions),metadata:hashText(stableStringify(data.metadata||{}))}))}`}
export function stableEntityHash(value){let h=2166136261;for(const c of String(value??'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36).toUpperCase()}
export function makeId(prefix,seed=''){if(crypto?.randomUUID)return `${prefix.toUpperCase()}:${crypto.randomUUID()}`;return `${prefix.toUpperCase()}:${Date.now().toString(36)}:${stableEntityHash(seed+Math.random())}`}
const germanAssoc=new Set(['Bayern','Baden','Berlin','Brandenburg','Bremen','Hamburg','Hessen','Mittelrhein','Mecklenburg-Vorpommern','Niederrhein','Niedersachsen','Rheinland','Saarland','Sachsen','Sachsen-Anhalt','Schleswig-Holstein','Südbaden','Südwest','Thüringen','Westfalen','Württemberg','Baden-Württemberg','NOFV','Rheinland-Pfalz']);
export function leagueNation(l){const c=String(l?.country||l?.nation||'').trim(),a=String(l?.association||'').trim(),r=String(l?.region||'').trim();if(c==='Deutschland'||a==='Deutschland'||r==='Deutschland'||germanAssoc.has(a)||germanAssoc.has(r))return 'Deutschland';return c||a||r||''}
function stableLegacy(prefix,db,parts,used){const b=`${prefix}_${stableEntityHash([db,...parts].join('|'))}`;let id=b,n=2;while(used.has(id))id=`${b}_${n++}`;used.add(id);return id}
export function ensureIds(data,databaseId='user:web'){
 for(const k of ['confederations','nations','leagues','leagueFlows','clubs','players','competitions'])data[k]=Array.isArray(data[k])?data[k]:[];data.metadata=data.metadata||{};
 const confIds=new Set();for(const c of data.confederations){let id=String(c.id||c.ruleId||'');if(!id||confIds.has(id))id=stableLegacy('CONF',databaseId,[c.name,c.displayName],confIds);else confIds.add(id);c.id=id;c.ruleId=c.ruleId||id;c.databaseId=databaseId}
 const nIds=new Set(),nByName=new Map();for(const n of data.nations){const name=String(n.name||n.displayName||'');let id=String(n.id||n.nationId||'');if(!id||nIds.has(id))id=stableLegacy('NATION',databaseId,[name,n.confederation],nIds);else nIds.add(id);n.id=n.nationId=id;n.databaseId=databaseId;if(name&&!nByName.has(name))nByName.set(name,n)}
 const lIds=new Set(),lByName=new Map();for(const l of data.leagues){const name=String(l.name||l.displayName||''),nation=leagueNation(l);let id=String(l.id||l.leagueId||'');if(!id||lIds.has(id))id=stableLegacy('LEAGUE',databaseId,[name,nation,l.level,l.region],lIds);else lIds.add(id);l.id=l.leagueId=id;l.databaseId=databaseId;const n=nByName.get(nation);if(n&&!l.nationId)l.nationId=n.id;if(nation&&!l.databaseNation)l.databaseNation=nation;if(name&&!lByName.has(name))lByName.set(name,l)}
 const cIds=new Set(),cById=new Map();for(const c of data.clubs){let id=String(c.id||c.clubId||'');if(!id||cIds.has(id))id=stableLegacy('CLUB',databaseId,[id,c.name,c.league,c.region],cIds);else cIds.add(id);c.id=c.clubId=id;c.databaseId=databaseId;const l=lByName.get(String(c.league||''));if(l&&!c.leagueId)c.leagueId=l.id;if(l&&!c.level)c.level=Number(l.level)||1;if(l&&!c.databaseNation)c.databaseNation=leagueNation(l);cById.set(id,c)}
 const pIds=new Set();for(const p of data.players){let id=String(p.id||p.playerId||'');if(!id||pIds.has(id))id=stableLegacy('PLAYER',databaseId,[id,p.name,p.clubId,p.birthDate,p.position],pIds);else pIds.add(id);p.id=p.playerId=id;p.databaseId=databaseId;if(p.clubId&&cById.has(String(p.clubId)))p.clubId=String(p.clubId)}
 const xIds=new Set();for(const x of data.competitions){const code=String(x.code||x.ruleId||x.name||'');let id=String(x.id||'');if(!id||xIds.has(id))id=stableLegacy('COMP',databaseId,[code,x.scope,x.confederation],xIds);else xIds.add(id);x.id=id;x.code=x.code||x.ruleId||id.replace(/^COMP:/i,'');x.ruleId=x.ruleId||x.code;x.databaseId=databaseId}
 data.metadata.databaseId=databaseId;data.metadata.schemaVersion=DB_SCHEMA_VERSION;return data
}
export function deriveConfederations(nations){const m=new Map();for(const n of nations||[]){const code=String(n.confederation||'FIFA').toUpperCase();if(!m.has(code))m.set(code,{id:code,ruleId:code,name:code,displayName:code,sortOrder:m.size,isBuiltInRule:true})}return [...m.values()]}
export function indexes(data){const nationByName=new Map(data.nations.map(x=>[String(x.name),x])),leagueByName=new Map(data.leagues.map(x=>[String(x.name),x])),leagueById=new Map(data.leagues.map(x=>[String(x.id),x])),clubById=new Map(data.clubs.map(x=>[String(x.id),x])),clubByLowerName=new Map(),playerById=new Map(),clubSearch=[];const clubsByLeague=new Map(),playersByClub=new Map();for(const c of data.clubs){const lid=String(c.leagueId||leagueByName.get(String(c.league||''))?.id||'');if(!clubsByLeague.has(lid))clubsByLeague.set(lid,[]);clubsByLeague.get(lid).push(c);const lower=String(c.name||'').trim().toLowerCase();if(lower&&!clubByLowerName.has(lower))clubByLowerName.set(lower,c);clubSearch.push({club:c,key:`${lower} ${String(c.id||'').toLowerCase()}`})}for(const p of data.players){const id=String(p.clubId||'');if(!playersByClub.has(id))playersByClub.set(id,[]);playersByClub.get(id).push(p);if(p?.id!=null)playerById.set(String(p.id),p)}return{nationByName,leagueByName,leagueById,clubById,clubByLowerName,playerById,clubSearch,clubsByLeague,playersByClub}}
export function validate(data){const issues=[],seen=(arr,type)=>{const s=new Set();for(const x of arr){if(!x?.id)issues.push({severity:'error',type,message:`${type} is missing an ID`,entity:x});else if(s.has(String(x.id)))issues.push({severity:'error',type,message:`Duplicate ${type} ID: ${x.id}`,entity:x});s.add(String(x.id))}};seen(data.nations,'Nation');seen(data.leagues,'League');seen(data.clubs,'Club');seen(data.players,'Player');const ix=indexes(data);for(const l of data.leagues)if(l.nationId&&!data.nations.some(n=>String(n.id)===String(l.nationId)))issues.push({severity:'error',type:'League',message:`${l.name}: missing nation ${l.nationId}`,entity:l});for(const c of data.clubs)if(c.leagueId&&!ix.leagueById.has(String(c.leagueId)))issues.push({severity:'error',type:'Club',message:`${c.name}: missing league ${c.leagueId}`,entity:c});for(const p of data.players)if(p.clubId&&!ix.clubById.has(String(p.clubId)))issues.push({severity:'error',type:'Player',message:`${p.firstName||''} ${p.lastName||p.name||''}: missing club ${p.clubId}`,entity:p});for(const l of data.leagues){const actual=ix.clubsByLeague.get(String(l.id))?.length||0;if(Number(l.teams||0)&&Number(l.teams)!==actual)issues.push({severity:'warning',type:'League',message:`${l.name}: stored team count ${l.teams}, actual ${actual}`,entity:l})}return issues}
export function ratingClass(v){v=Number(v||0);return v>=85?'elite':v>=78?'high':v>=70?'good':v>=60?'mid':'low'}
export function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
export function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
